import { LibraryAutomation } from "../types";

export const MOCK_LIBRARY_AUTOMATIONS: LibraryAutomation[] = [
  {
    id: "1",
    name: "Product Interest Targeted Follow-Up",
    iconKey: "featuredIcon1",
    category: "Sales and Lead Generation",
    businessGoal: "Marketing Lead Strategy",
    status: "active",
    lastEdited: "10/11/2025 19:47",
    currentContact: 2,
  },
  {
    id: "2",
    name: "Customer Support Escalation Flow",
    iconKey: "featuredIcon2",
    category: "Support and Escalation",
    businessGoal: "Support Efficiency",
    status: "inactive",
    lastEdited: "10/11/2025 19:47",
    currentContact: 0,
  },
  {
    id: "3",
    name: "New User Onboarding Sequence",
    iconKey: "featuredIcon3",
    category: "Retention and Nurture",
    businessGoal: "Customer Success",
    status: "active",
    lastEdited: "11/11/2025 09:30",
    currentContact: 15,
  },
  {
    id: "4",
    name: "Holiday Promo Campaign",
    iconKey: "featuredIcon4",
    category: "Re-engagement and Campaigns",
    businessGoal: "Sales Conversion",
    status: "active",
    lastEdited: "12/11/2025 14:20",
    currentContact: 45,
  },
  {
    id: "5",
    name: "Abandoned Cart Recovery",
    iconKey: "featuredIcon1",
    category: "Sales and Lead Generation",
    businessGoal: "Marketing Lead Strategy",
    status: "active",
    lastEdited: "13/11/2025 11:15",
    currentContact: 8,
  },
  {
    id: "6",
    name: "VIP Appreciation Reward",
    iconKey: "featuredIcon3",
    category: "Retention and Nurture",
    businessGoal: "Customer Retention",
    status: "active",
    lastEdited: "14/11/2025 16:45",
    currentContact: 12,
  },
  {
    id: "7",
    name: "Re-activation Outreach",
    iconKey: "featuredIcon4",
    category: "Re-engagement and Campaigns",
    businessGoal: "Re-engagement",
    status: "inactive",
    lastEdited: "15/11/2025 10:00",
    currentContact: 0,
  },
  {
    id: "8",
    name: "High Priority Ticket Alert",
    iconKey: "featuredIcon2",
    category: "Support and Escalation",
    businessGoal: "Support Escalation",
    status: "active",
    lastEdited: "16/11/2025 08:00",
    currentContact: 3,
  },
];
