export const EMAIL_COMPOSER_TOOLS = (icons: Record<string, string>) => [
  { id: "lines", src: icons.lines, alt: "alignment", command: "justifyFull" },
  { id: "bold", src: icons.bold, alt: "bold", command: "bold" },
  { id: "italic", src: icons.italic, alt: "italic", command: "italic" },
  {
    id: "underline",
    src: icons.underline,
    alt: "underline",
    command: "underline",
  },
  { id: "undo", src: icons.curvyLeft, alt: "undo", command: "undo" },
  { id: "redo", src: icons.curvyRight, alt: "redo", command: "redo" },
  {
    id: "list-ordered",
    src: icons.lists,
    alt: "ordered list",
    command: "insertOrderedList",
  },
  {
    id: "list-unordered",
    src: icons.listsUnordered,
    alt: "unordered list",
    command: "insertUnorderedList",
  },
  { id: "link", src: icons.linkChain, alt: "link", command: "createLink" },
  { id: "emoji", src: icons.emoji, alt: "emoji", command: "emoji" },
  { id: "gallery", src: icons.gallery, alt: "gallery", command: "gallery" },
];

export const EMOJIS = [
  "😊",
  "😂",
  "🥰",
  "😎",
  "🤔",
  "🔥",
  "👍",
  "🙌",
  "📍",
  "✉️",
  "🚀",
  "💡",
  "✅",
  "❌",
  "✨",
  "🎉",
  "👨‍💻",
  "👩‍💻",
  "💼",
  "📈",
  "❤️",
  "😮",
  "😢",
  "👏",
  "🤝",
  "💪",
  "🌈",
  "☀️",
  "🌙",
  "⭐",
  "🔔",
  "📅",
  "📎",
  "📌",
  "🔍",
  "📱",
  "💻",
  "🎨",
  "🎵",
  "📷",
  "🤝",
  "🙏",
  "✌️",
  "🤘",
  "👋",
  "🖖",
  "🖐️",
  "✋",
  "✍️",
  "🤳",
];
