import { Conversation, InboxType } from "../types";

export const inboxTypeLabels: Record<InboxType, string> = {
  general: "General Inbox",
  team: "Team Inbox",
};

export const generalInboxConversations: Conversation[] = [
  {
    id: "1",
    name: "Alice Miles",
    tagId: "wishlist-user",
    tag: "Wishlist-user",
    preview: "I want to know if the price is negotiable, i need about 2 Units",
    timestamp: "2 days ago",
    avatarColor: "bg-green-500",
    avatarUrl: "https://i.pravatar.cc/150?img=1",
    channel: "whatsapp",
    unreadCount: 3,
    labelIds: ["label-4"],
    assignedTo: [
      {
        id: "user-1",
        name: "Sarah Mitchell",
        avatarUrl: "https://i.pravatar.cc/150?img=47",
        email: "sarah.mitchell@company.com",
      },
      {
        id: "user-2",
        name: "Mike Johnson",
        avatarUrl: "https://i.pravatar.cc/150?img=32",
        email: "mike.johnson@company.com",
      },
    ],
  },
  {
    id: "2",
    name: "Brian George",
    tagId: "new-customer",
    tag: "New customer",
    preview: "I want to know if the price is negotiable, i need about 2 Units",
    timestamp: "1 min ago",
    avatarColor: "bg-blue-500",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    channel: "telegram",
    unreadCount: 2,
    labelIds: ["label-1"],
    assignedTo: [
      {
        id: "user-3",
        name: "Emma Davis",
        avatarUrl: "https://i.pravatar.cc/150?img=20",
        email: "emma.davis@company.com",
      },
    ],
  },
  {
    id: "3",
    name: "Elijah Nnabuife",
    tagId: "chat-responded",
    tag: "chat-responded",
    preview: "I want to know if the price is negotiable, i need about 2 Units",
    timestamp: "3 days ago",
    avatarColor: "bg-purple-500",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
    channel: "facebook",
    unreadCount: 5,
  },
  {
    id: "4",
    name: "Nicolas Jackson",
    tagId: "viewed-product",
    tag: "Viewed-product",
    preview: "I want to know if the price is negotiable, i need about 2 Units",
    timestamp: "1 day ago",
    avatarColor: "bg-yellow-500",
    avatarUrl: "https://i.pravatar.cc/150?img=33",
    channel: "website-chat",
    unreadCount: 1,
    labelIds: ["label-2"],
    assignedTo: [
      {
        id: "user-1",
        name: "Sarah Mitchell",
        avatarUrl: "https://i.pravatar.cc/150?img=47",
        email: "sarah.mitchell@company.com",
      },
      {
        id: "user-4",
        name: "David Chen",
        avatarUrl: "https://i.pravatar.cc/150?img=14",
        email: "david.chen@company.com",
      },
      {
        id: "user-5",
        name: "Jennifer Taylor",
        avatarUrl: "https://i.pravatar.cc/150?img=9",
        email: "jennifer.taylor@company.com",
      },
    ],
  },
  {
    id: "5",
    name: "Dan James",
    tagId: "new-customer",
    tag: "New customer",
    preview: "I want to know if the price is negotiable, i need about 2 Units",
    timestamp: "2 hours ago",
    avatarColor: "bg-red-500",
    avatarUrl: "https://i.pravatar.cc/150?img=45",
    channel: "instagram",
    unreadCount: 0,
    labelIds: ["label-3"],
  },
  {
    id: "6",
    name: "Malcom X",
    tagId: "facebook-ad",
    tag: "facebook-ad",
    preview: "I want to know if the price is negotiable, i need about 2 Units",
    timestamp: "5 hours ago",
    avatarColor: "bg-indigo-500",
    avatarUrl: "https://i.pravatar.cc/150?img=16",
    channel: "facebook",
    unreadCount: 3,
  },
  {
    id: "7",
    name: "Micheal Jordan",
    tagId: "viewed-product",
    tag: "Viewed-product",
    preview: "I want to know if the price is negotiable, i need about 2 Units",
    timestamp: "1 day ago",
    avatarColor: "bg-cyan-500",
    avatarUrl: "https://i.pravatar.cc/150?img=23",
    channel: "facebook",
    unreadCount: 0,
  },
  {
    id: "8",
    name: "Sarah Johnson",
    tagId: "wishlist-user",
    tag: "Wishlist-user",
    preview:
      "Hello! I'm interested in your premium package. Can you tell me more about the features?",
    timestamp: "30 minutes ago",
    avatarColor: "bg-pink-500",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    channel: "whatsapp",
    unreadCount: 1,
    labelIds: ["label-2"],
    assignedTo: [
      {
        id: "user-2",
        name: "Mike Johnson",
        avatarUrl: "https://i.pravatar.cc/150?img=32",
        email: "mike.johnson@company.com",
      },
      {
        id: "user-6",
        name: "Chris Thompson",
        avatarUrl: "https://i.pravatar.cc/150?img=15",
        email: "chris.thompson@company.com",
      },
    ],
  },
  {
    id: "9",
    name: "Robert Chen",
    tagId: "new-customer",
    tag: "New customer",
    preview: "I saw your ad on Instagram. Do you ship internationally?",
    timestamp: "4 hours ago",
    avatarColor: "bg-teal-500",
    avatarUrl: "https://i.pravatar.cc/150?img=14",
    channel: "instagram",
    unreadCount: 2,
  },
  {
    id: "10",
    name: "Emma Wilson",
    tagId: "chat-responded",
    preview:
      "Thank you for the quick response! I'm very satisfied with the service.",
    timestamp: "6 hours ago",
    avatarColor: "bg-orange-500",
    avatarUrl: "https://i.pravatar.cc/150?img=9",
    channel: "email",
    unreadCount: 0,
  },
  {
    id: "11",
    name: "James Rodriguez",
    tagId: "vip-customer",
    tag: "Vip-customer",
    preview: "I'd like to place a bulk order. Can we discuss pricing?",
    timestamp: "12 hours ago",
    avatarColor: "bg-amber-500",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    channel: "linkedin",
    unreadCount: 0,
    labelIds: ["label-3"],
    assignedTo: [
      {
        id: "user-7",
        name: "Lisa Anderson",
        avatarUrl: "https://i.pravatar.cc/150?img=5",
        email: "lisa.anderson@company.com",
      },
    ],
  },
  {
    id: "12",
    name: "Lisa Anderson",
    tagId: "returning-customer",
    tag: "Returning-customer",
    preview: "I'm having an issue with my recent order. Order #12345",
    timestamp: "1 hour ago",
    avatarColor: "bg-rose-500",
    avatarUrl: "https://i.pravatar.cc/150?img=20",
    channel: "whatsapp",
    unreadCount: 1,
    labelIds: ["label-5"],
    assignedTo: [
      {
        id: "user-1",
        name: "Sarah Mitchell",
        avatarUrl: "https://i.pravatar.cc/150?img=47",
        email: "sarah.mitchell@company.com",
      },
      {
        id: "user-3",
        name: "Emma Davis",
        avatarUrl: "https://i.pravatar.cc/150?img=20",
        email: "emma.davis@company.com",
      },
      {
        id: "user-4",
        name: "David Chen",
        avatarUrl: "https://i.pravatar.cc/150?img=14",
        email: "david.chen@company.com",
      },
    ],
  },
  {
    id: "13",
    name: "David Kim",
    tagId: "viewed-product",
    tag: "Viewed-product",
    preview: "What's the warranty period for this product?",
    timestamp: "3 hours ago",
    avatarColor: "bg-violet-500",
    avatarUrl: "https://i.pravatar.cc/150?img=21",
    channel: "telegram",
    unreadCount: 0,
  },
  {
    id: "14",
    name: "Maria Garcia",
    tagId: "new-customer",
    preview: "Hi! I'm interested in your services. Can you send me a quote?",
    timestamp: "45 minutes ago",
    avatarColor: "bg-emerald-500",
    avatarUrl: "https://i.pravatar.cc/150?img=22",
    channel: "sms",
    unreadCount: 1,
    labelIds: ["label-4"],
  },
  {
    id: "15",
    name: "Tom Anderson",
    tagId: "facebook-ad",
    tag: "facebook-ad",
    preview: "Saw your Facebook ad. When will the new collection be available?",
    timestamp: "2 hours ago",
    avatarColor: "bg-sky-500",
    avatarUrl: "https://i.pravatar.cc/150?img=24",
    channel: "facebook",
    unreadCount: 0,
  },
];

export const teamInboxConversations: Conversation[] = [
  {
    id: "t1",
    name: "Sarah Mitchell",
    preview:
      "Can we schedule a call to discuss the Q4 strategy? I have some ideas to share.",
    timestamp: "30 minutes ago",
    avatarColor: "bg-green-500",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
    unreadCount: 2,
  },
  {
    id: "t2",
    name: "Mike Johnson",
    preview:
      "The client feedback has been incorporated. Ready for your review.",
    timestamp: "1 hour ago",
    avatarColor: "bg-indigo-500",
    avatarUrl: "https://i.pravatar.cc/150?img=32",
    unreadCount: 0,
  },
  {
    id: "t3",
    name: "Emma Davis",
    preview:
      "Can you review the latest design mockups? Need your approval before we proceed.",
    timestamp: "2 hours ago",
    avatarColor: "bg-pink-500",
    avatarUrl: "https://i.pravatar.cc/150?img=20",
    unreadCount: 1,
  },
  {
    id: "t4",
    name: "David Chen",
    preview:
      "I need clarification on the pricing structure for the new product line.",
    timestamp: "3 hours ago",
    avatarColor: "bg-teal-500",
    avatarUrl: "https://i.pravatar.cc/150?img=14",
    unreadCount: 0,
  },
  {
    id: "t5",
    name: "Jennifer Taylor",
    preview:
      "The team meeting is scheduled for tomorrow at 2 PM. Please confirm your attendance.",
    timestamp: "4 hours ago",
    avatarColor: "bg-orange-500",
    avatarUrl: "https://i.pravatar.cc/150?img=9",
    unreadCount: 0,
  },
  {
    id: "t6",
    name: "Chris Thompson",
    preview:
      "The budget proposal has been sent. Let me know if you need any adjustments.",
    timestamp: "5 hours ago",
    avatarColor: "bg-cyan-500",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    unreadCount: 0,
  },
  {
    id: "t7",
    name: "Lisa Anderson",
    preview:
      "I've completed the market research. The report is ready for review.",
    timestamp: "6 hours ago",
    avatarColor: "bg-purple-500",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    unreadCount: 0,
  },
  {
    id: "t8",
    name: "Robert Wilson",
    preview:
      "The project timeline needs to be updated. Can we discuss this in detail?",
    timestamp: "1 day ago",
    avatarColor: "bg-blue-500",
    avatarUrl: "https://i.pravatar.cc/150?img=13",
    unreadCount: 3,
  },
  {
    id: "tg1",
    name: "Design Team",
    preview:
      "Sarah: Can we discuss the new branding guidelines in our team meeting tomorrow?",
    timestamp: "1 hour ago",
    avatarColor: "bg-purple-500",
    unreadCount: 5,
    isGroup: true,
    participants: ["Sarah", "Mike", "Emma", "You"],
    participantAvatars: [
      "https://i.pravatar.cc/150?img=47",
      "https://i.pravatar.cc/150?img=32",
      "https://i.pravatar.cc/150?img=20",
    ],
    participantCount: 4,
  },
  {
    id: "tg2",
    name: "Project Alpha",
    preview:
      "John: The client approved the latest changes! We can proceed to the next phase.",
    timestamp: "2 hours ago",
    avatarColor: "bg-blue-500",
    unreadCount: 8,
    isGroup: true,
    participants: ["John", "Lisa", "David", "You", "Sarah"],
    participantAvatars: [
      "https://i.pravatar.cc/150?img=12",
      "https://i.pravatar.cc/150?img=5",
      "https://i.pravatar.cc/150?img=14",
      "https://i.pravatar.cc/150?img=47",
    ],
    participantCount: 5,
  },
  {
    id: "tg3",
    name: "Marketing Campaign",
    preview:
      "Emma: Let's finalize the launch date this week. I've sent the calendar invites.",
    timestamp: "3 hours ago",
    avatarColor: "bg-pink-500",
    unreadCount: 0,
    isGroup: true,
    participants: ["Emma", "Tom", "You"],
    participantAvatars: [
      "https://i.pravatar.cc/150?img=20",
      "https://i.pravatar.cc/150?img=16",
    ],
    participantCount: 3,
  },
  {
    id: "tg4",
    name: "Sales Team",
    preview:
      "Mike: The quarterly targets have been updated. Check the dashboard for details.",
    timestamp: "4 hours ago",
    avatarColor: "bg-green-500",
    unreadCount: 2,
    isGroup: true,
    participants: ["Mike", "Jennifer", "Chris", "You", "Sarah"],
    participantAvatars: [
      "https://i.pravatar.cc/150?img=32",
      "https://i.pravatar.cc/150?img=9",
      "https://i.pravatar.cc/150?img=15",
      "https://i.pravatar.cc/150?img=47",
    ],
    participantCount: 5,
  },
  {
    id: "tg5",
    name: "Product Development",
    preview:
      "David: The beta testing phase is complete. Ready for production release.",
    timestamp: "5 hours ago",
    avatarColor: "bg-indigo-500",
    unreadCount: 1,
    isGroup: true,
    participants: ["David", "Emma", "Mike", "You"],
    participantAvatars: [
      "https://i.pravatar.cc/150?img=14",
      "https://i.pravatar.cc/150?img=20",
      "https://i.pravatar.cc/150?img=32",
    ],
    participantCount: 4,
  },
  {
    id: "tg6",
    name: "Customer Support",
    preview:
      "Lisa: We've resolved 95% of the tickets this week. Great work team!",
    timestamp: "6 hours ago",
    avatarColor: "bg-teal-500",
    unreadCount: 0,
    isGroup: true,
    participants: ["Lisa", "Sarah", "Chris", "You", "Jennifer"],
    participantAvatars: [
      "https://i.pravatar.cc/150?img=5",
      "https://i.pravatar.cc/150?img=47",
      "https://i.pravatar.cc/150?img=15",
      "https://i.pravatar.cc/150?img=9",
    ],
    participantCount: 5,
  },
  {
    id: "tg7",
    name: "Engineering Team",
    preview:
      "Robert: The deployment is scheduled for tonight. All systems are ready.",
    timestamp: "1 day ago",
    avatarColor: "bg-cyan-500",
    unreadCount: 4,
    isGroup: true,
    participants: ["Robert", "David", "Mike", "You"],
    participantAvatars: [
      "https://i.pravatar.cc/150?img=13",
      "https://i.pravatar.cc/150?img=14",
      "https://i.pravatar.cc/150?img=32",
    ],
    participantCount: 4,
  },
];
