import { TableRow } from "../types";

export const generateAutomationsData = (icons: {
  autoImg1: string;
  autoImg2: string;
  autoImg3: string;
}): TableRow[] => {
  const iconList = [icons.autoImg1, icons.autoImg2, icons.autoImg3];

  const getRandomInt = (min: number, max: number): number =>
    Math.floor(Math.random() * (max - min + 1)) + min;

  const createTableRow = (
    id: string,
    name: string,
    type: string,
    description: string,
    index: number,
  ): TableRow => ({
    id,
    name,
    icon: iconList[index % 3],
    contact: getRandomInt(100, 1200),
    campaign: getRandomInt(10, 100),
    conversion: getRandomInt(5, 100),
    type,
    description,
    status: Math.random() > 0.5 ? "active" : "inactive",
  });

  const categoryTemplates = {
    "Sales and Lead Generation": {
      names: [
        "Prospect Nurture Bot",
        "Cold Email Outreach",
        "Inbound Lead Router",
        "Sales Funnel Optimizer",
        "Cross-Sell Trigger",
        "Account-Based Marketing",
        "Lead Magnet Distributor",
        "Pipeline Accelerator",
        "Engagement Tracker",
        "Quote Generator",
      ],
      descriptions: [
        "Automates follow-ups for high-potential prospects",
        "Personalizes outreach based on user behavior",
        "Routes inbound leads to the right sales rep",
        "Optimizes funnel stages for higher conversions",
        "Triggers cross-sell offers post-purchase",
        "Targets key accounts with tailored campaigns",
        "Distributes lead magnets to capture emails",
        "Speeds up deals through automated nudges",
        "Tracks engagement signals for lead prioritization",
        "Generates instant quotes for prospects",
      ],
    },
    "Support and Escalation": {
      names: [
        "Issue Resolver Bot",
        "Support Queue Manager",
        "SLA Monitor",
        "Feedback Loop",
        "Case Prioritizer",
        "Knowledge Base Suggester",
        "Agent Assist AI",
        "Ticket Auto-Tagger",
        "Resolution Tracker",
        "Support Chatbot",
      ],
      descriptions: [
        "Resolves common issues via AI responses",
        "Manages support queues for faster response",
        "Alerts team when SLAs are at risk",
        "Collects feedback after ticket resolution",
        "Prioritizes cases based on severity",
        "Suggests relevant KB articles to users",
        "Assists agents with real-time suggestions",
        "Tags tickets automatically for routing",
        "Tracks resolution times for analytics",
        "Handles initial customer inquiries via chat",
      ],
    },
    "Retention and Nurture": {
      names: [
        "Engagement Booster",
        "Milestone Rewarder",
        "Usage Monitor",
        "Renewal Nudger",
        "VIP Customer Flow",
        "Product Tour Guide",
        "Loyalty Campaign",
        "Onboarding Mentor",
        "Feature Promoter",
        "Retention Analyzer",
      ],
      descriptions: [
        "Boosts engagement with timely prompts",
        "Rewards users for hitting key milestones",
        "Monitors usage to prevent churn",
        "Sends reminders for upcoming renewals",
        "Delivers exclusive perks to VIP customers",
        "Guides users through product tours",
        "Automates loyalty program communications",
        "Mentors new users during onboarding",
        "Promotes underused features to users",
        "Analyzes retention metrics for insights",
      ],
    },
    "Re-engagement and Campaigns": {
      names: [
        "Win-Back Campaign",
        "Promo Code Blaster",
        "Event Inviter",
        "Dormant User Nudge",
        "Upsell Trigger",
        "Holiday Sale Bot",
        "Cart Reminder",
        "Engagement Reboot",
        "Beta Tester Recruiter",
        "Limited Offer Pusher",
      ],
      descriptions: [
        "Targets lapsed users with win-back offers",
        "Sends promo codes to boost sales",
        "Invites users to webinars and events",
        "Nudges inactive users with incentives",
        "Triggers upsell offers for active users",
        "Automates holiday-specific promotions",
        "Reminds users about abandoned carts",
        "Reboots engagement with fresh campaigns",
        "Recruits users for beta testing",
        "Pushes time-sensitive offers to users",
      ],
    },
    "Internal Operations & Admin": {
      names: [
        "Task Automator",
        "Approval Workflow",
        "Resource Allocator",
        "Compliance Checker",
        "Inventory Sync",
        "Team Notifier",
        "Budget Tracker",
        "Access Manager",
        "Event Scheduler",
        "Data Cleaner",
      ],
      descriptions: [
        "Automates repetitive internal tasks",
        "Streamlines approval processes",
        "Allocates resources based on need",
        "Checks for compliance issues",
        "Syncs inventory data across systems",
        "Notifies teams of critical updates",
        "Tracks budget usage automatically",
        "Manages user access permissions",
        "Schedules internal events and meetings",
        "Cleans stale data from databases",
      ],
    },
  };

  const originalData: TableRow[] = [
    // Sales and Lead Generation (5 entries)
    {
      id: "1",
      name: "Lead Qualification Bot",
      icon: icons.autoImg1,
      contact: 123,
      campaign: 45,
      conversion: 12,
      type: "Sales and Lead Generation",
      description: "AI-powered bot qualifies leads by engagement & intent",
      status: "active",
    },
    {
      id: "2",
      name: "Welcome Sequence",
      icon: icons.autoImg2,
      contact: 456,
      campaign: 67,
      conversion: 23,
      type: "Sales and Lead Generation",
      description: "Multi-touch welcome journey for new signups",
      status: "inactive",
    },
    {
      id: "3",
      name: "Lead Scoring Automation",
      icon: icons.autoImg3,
      contact: 789,
      campaign: 89,
      conversion: 34,
      type: "Sales and Lead Generation",
      description: "Dynamic scoring based on behavior, firmographics & fit",
      status: "active",
    },
    {
      id: "4",
      name: "Demo Request Funnel",
      icon: icons.autoImg1,
      contact: 612,
      campaign: 78,
      conversion: 41,
      type: "Sales and Lead Generation",
      description: "Auto-schedules demos for high-intent leads",
      status: "inactive",
    },
    {
      id: "5",
      name: "Referral Booster",
      icon: icons.autoImg2,
      contact: 398,
      campaign: 52,
      conversion: 29,
      type: "Sales and Lead Generation",
      description: "Triggers referral asks after successful conversions",
      status: "active",
    },
    // Support and Escalation (5 entries)
    {
      id: "6",
      name: "Ticket Triage System",
      icon: icons.autoImg1,
      contact: 101,
      campaign: 12,
      conversion: 5,
      type: "Support and Escalation",
      description: "Routes tickets by urgency, product & agent skill",
      status: "inactive",
    },
    {
      id: "7",
      name: "Customer Feedback Collector",
      icon: icons.autoImg2,
      contact: 112,
      campaign: 34,
      conversion: 18,
      type: "Support and Escalation",
      description: "Post-resolution NPS + open-ended feedback",
      status: "active",
    },
    {
      id: "8",
      name: "Escalation Manager",
      icon: icons.autoImg1,
      contact: 223,
      campaign: 56,
      conversion: 29,
      type: "Support and Escalation",
      description: "Auto-escalates unresolved tickets with SLA alerts",
      status: "inactive",
    },
    {
      id: "9",
      name: "Self-Service Deflector",
      icon: icons.autoImg3,
      contact: 187,
      campaign: 41,
      conversion: 22,
      type: "Support and Escalation",
      description: "Offers knowledge base articles before ticket creation",
      status: "active",
    },
    {
      id: "10",
      name: "Live Chat Handoff",
      icon: icons.autoImg2,
      contact: 134,
      campaign: 28,
      conversion: 15,
      type: "Support and Escalation",
      description: "Seamlessly hands off bot chats to human agents",
      status: "inactive",
    },
    // Retention and Nurture (5 entries)
    {
      id: "11",
      name: "Churn Prevention",
      icon: icons.autoImg2,
      contact: 334,
      campaign: 78,
      conversion: 41,
      type: "Retention and Nurture",
      description: "Predicts churn risk & triggers win-back flows",
      status: "active",
    },
    {
      id: "12",
      name: "Loyalty Rewards",
      icon: icons.autoImg3,
      contact: 445,
      campaign: 90,
      conversion: 52,
      type: "Retention and Nurture",
      description: "Points, tiers, and exclusive perks automation",
      status: "inactive",
    },
    {
      id: "13",
      name: "Customer Onboarding",
      icon: icons.autoImg1,
      contact: 556,
      campaign: 23,
      conversion: 63,
      type: "Retention and Nurture",
      description: "Drip campaign + milestone celebrations",
      status: "active",
    },
    {
      id: "14",
      name: "Feature Adoption Coach",
      icon: icons.autoImg2,
      contact: 489,
      campaign: 67,
      conversion: 58,
      type: "Retention and Nurture",
      description: "Guides users to activate high-value features",
      status: "inactive",
    },
    {
      id: "15",
      name: "Anniversary Celebrator",
      icon: icons.autoImg3,
      contact: 267,
      campaign: 44,
      conversion: 37,
      type: "Retention and Nurture",
      description: "Sends personalized gifts on customer anniversaries",
      status: "active",
    },
    // Re-engagement and Campaigns (5 entries)
    {
      id: "16",
      name: "Abandoned Cart Recovery",
      icon: icons.autoImg1,
      contact: 667,
      campaign: 45,
      conversion: 74,
      type: "Re-engagement and Campaigns",
      description: "Multi-channel recovery: email → SMS → push",
      status: "inactive",
    },
    {
      id: "17",
      name: "Seasonal Campaign Manager",
      icon: icons.autoImg2,
      contact: 778,
      campaign: 67,
      conversion: 85,
      type: "Re-engagement and Campaigns",
      description: "Black Friday, Valentine's, Back-to-School — all automated",
      status: "active",
    },
    {
      id: "18",
      name: "Inactive User Reactivation",
      icon: icons.autoImg3,
      contact: 889,
      campaign: 89,
      conversion: 96,
      type: "Re-engagement and Campaigns",
      description: "Personalized 'We Miss You' with exclusive offer",
      status: "inactive",
    },
    {
      id: "19",
      name: "Sunset Product Migrator",
      icon: icons.autoImg1,
      contact: 512,
      campaign: 61,
      conversion: 68,
      type: "Re-engagement and Campaigns",
      description: "Migrates users from deprecated to new plans",
      status: "active",
    },
    {
      id: "20",
      name: "Flash Sale Blaster",
      icon: icons.autoImg2,
      contact: 723,
      campaign: 83,
      conversion: 91,
      type: "Re-engagement and Campaigns",
      description: "24-hour flash sales with countdown timers",
      status: "inactive",
    },
    // Internal Operations & Admin (5 entries)
    {
      id: "21",
      name: "Employee Onboarding",
      icon: icons.autoImg3,
      contact: 990,
      campaign: 12,
      conversion: 17,
      type: "Internal Operations & Admin",
      description: "IT setup, HR docs, Slack invites — all automated",
      status: "active",
    },
    {
      id: "22",
      name: "Report Generator",
      icon: icons.autoImg1,
      contact: 1011,
      campaign: 34,
      conversion: 28,
      type: "Internal Operations & Admin",
      description: "Daily/weekly KPI dashboards to Slack & email",
      status: "inactive",
    },
    {
      id: "23",
      name: "Data Sync Manager",
      icon: icons.autoImg2,
      contact: 1122,
      campaign: 56,
      conversion: 39,
      type: "Internal Operations & Admin",
      description: "Bi-directional sync: CRM ↔ Billing ↔ Support",
      status: "active",
    },
    {
      id: "24",
      name: "Contract Renewal Bot",
      icon: icons.autoImg3,
      contact: 834,
      campaign: 48,
      conversion: 33,
      type: "Internal Operations & Admin",
      description: "90-60-30 day renewal reminders with upsell",
      status: "inactive",
    },
    {
      id: "25",
      name: "Security Alert Relay",
      icon: icons.autoImg1,
      contact: 156,
      campaign: 19,
      conversion: 11,
      type: "Internal Operations & Admin",
      description: "Forwards critical security events to SOC team",
      status: "active",
    },
  ];

  const result: TableRow[] = [...originalData];
  let idCounter = 26;

  Object.keys(categoryTemplates).forEach((type) => {
    const { names, descriptions } =
      categoryTemplates[type as keyof typeof categoryTemplates];
    // Generate 95 additional entries (100 total - 5 original)
    for (let i = 0; i < 95; i++) {
      const nameIndex = i % names.length;
      const descIndex = i % descriptions.length;
      const name = `${names[nameIndex]} ${String(i + 1).padStart(2, "0")}`;
      const description = descriptions[descIndex];
      result.push(
        createTableRow(String(idCounter++), name, type, description, i),
      );
    }
  });

  return result;
};
