import { TemplateFormData } from "../types";

export interface Template {
  id: string;
  title: string;
  description: string;
  category: string;
  formData: TemplateFormData;
}

export const DISCOVER_TEMPLATES: Template[] = [
  {
    id: "smart-follow-up",
    title: "Smart Follow-Up",
    description:
      "Automatically re-engage contacts who haven't replied and move conversations forward without sounding pushy.",
    category: "General",
    formData: {
      account: "",
      name: "Smart Follow-Up",
      category: "MARKETING",
      language: "en_US",
      message:
        "Hi {{First Name}} Just checking in — wanted to be sure you saw my last message about service. Let me know if you need any help.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Use Template" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "missed-call-chat",
    title: "Missed Call -> Chat",
    description:
      "Turn missed calls into WhatsApp conversations instantly and keep leads from going cold.",
    category: "General",
    formData: {
      account: "",
      name: "Missed Call Chat",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, I saw we just missed a call from you. How can we help you today?",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Call me back" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "business-hours-auto-reply",
    title: "Business Hours Auto-Reply",
    description:
      "Acknowledge messages outside business hours and set clear expectations for response time.",
    category: "General",
    formData: {
      account: "",
      name: "Auto Reply",
      category: "UTILITY",
      language: "en_US",
      message:
        "Thanks for contacting us! We are currently closed. We will get back to you as soon as we open.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Visit Website" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "quick-feedback-check",
    title: "Quick Feedback Check",
    description:
      "Collect simple customer feedback after interactions to improve service quality and retention.",
    category: "General",
    formData: {
      account: "",
      name: "Feedback Check",
      category: "MARKETING",
      language: "en_US",
      message:
        "Hi {{First Name}}, how was your experience with us today? We'd love to hear your thoughts!",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [
        { type: "Quick reply", text: "Good" },
        { type: "Quick reply", text: "Bad" },
      ],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "abandoned-cart",
    title: "Abandoned Cart Reminder",
    description:
      "Nudge customers to complete their purchase with a friendly, high-converting reminder.",
    category: "E-commerce / Retail",
    formData: {
      account: "",
      name: "Abandoned Cart",
      category: "MARKETING",
      language: "en_US",
      message:
        "Hi {{First Name}}, we noticed you left some items in your cart. Don't miss out! Complete your purchase now.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Complete Checkout" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "order-confirmation",
    title: "Order Confirmation",
    description:
      "Confirm successful orders and reassure customers with clear next steps.",
    category: "E-commerce / Retail",
    formData: {
      account: "",
      name: "Order Confirmation",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, thanks for your order! We've received it and are processing it now. We'll send update soon.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Track Order" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "new-arrival-alert",
    title: "New Arrival Alert",
    description:
      "Notify customers about new products regarding their previous purchases.",
    category: "E-commerce / Retail",
    formData: {
      account: "",
      name: "New Arrival",
      category: "MARKETING",
      language: "en_US",
      message:
        "Hi {{First Name}}, Check out our new collection! We have something special just for you.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "View Collection" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "flash-sale",
    title: "Flash Sale Announcement",
    description:
      "Create urgency with a limited-time sale announcement for your customers.",
    category: "E-commerce / Retail",
    formData: {
      account: "",
      name: "Flash Sale",
      category: "MARKETING",
      language: "en_US",
      message:
        "Hi {{First Name}}, Our Flash Sale is live! Get up to 50% off for the next 24 hours.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Shop Now" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "property-viewing-reminder",
    title: "Viewing Reminder",
    description:
      "Remind clients about their upcoming property viewing appointment.",
    category: "Real Estate",
    formData: {
      account: "",
      name: "Viewing Reminder",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, this is a reminder for your property viewing tomorrow at 10 AM. See you there!",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Confirm" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "new-listing",
    title: "New Listing Alert",
    description: "Share new properties that match your client's preferences.",
    category: "Real Estate",
    formData: {
      account: "",
      name: "New Listing",
      category: "MARKETING",
      language: "en_US",
      message:
        "Hi {{First Name}}, a new property matching your criteria just hit the market. Check it out!",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "View Property" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "open-house-invite",
    title: "Open House Invite",
    description: "Invite potential buyers to an exclusive open house event.",
    category: "Real Estate",
    formData: {
      account: "",
      name: "Open House",
      category: "MARKETING",
      language: "en_US",
      message:
        "Hi {{First Name}}, you're invited to our Open House this Sunday at 2 PM. We'd love to see you!",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "RSVP" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "course-welcome",
    title: "Course Welcome",
    description:
      "Welcome new students and provide them with starting materials.",
    category: "Education / Online Courses",
    formData: {
      account: "",
      name: "Course Welcome",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, welcome to the course! We're excited to have you. Here is your login link.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Login" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "webinar-reminder",
    title: "Webinar Reminder",
    description:
      "Send a timely reminder to maximize attendance for your webinar.",
    category: "Education / Online Courses",
    formData: {
      account: "",
      name: "Webinar Reminder",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, our live webinar starts in 1 hour. Don't miss out on the Q&A session!",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Join Now" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "course-completion",
    title: "Course Completion",
    description:
      "Congratulate students on finishing a course and suggest next steps.",
    category: "Education / Online Courses",
    formData: {
      account: "",
      name: "Course Completion",
      category: "MARKETING",
      language: "en_US",
      message:
        "Congrats {{First Name}}! You've completed the course. Download your certificate now.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Download" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "payment-reminder",
    title: "Payment Reminder",
    description: "Gentle reminder for upcoming or overdue invoice payments.",
    category: "Finance / Accounting",
    formData: {
      account: "",
      name: "Payment Reminder",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, just a friendly reminder that Invoice #1234 is due tomorrow.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Pay Now" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "tax-deadline",
    title: "Tax Deadline Alert",
    description: "Notify clients about important tax filing deadlines.",
    category: "Finance / Accounting",
    formData: {
      account: "",
      name: "Tax Deadline",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, tax filing season is ending soon. Book a consultation to ensure you're ready.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Book Now" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "consultation-booking",
    title: "Consultation Confirm",
    description: "Confirm legal consultation details with your client.",
    category: "Legal Services",
    formData: {
      account: "",
      name: "Consultation Confirm",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, your consultation is confirmed for Tuesday at 2 PM. Please bring your ID.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Okay" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "document-signed",
    title: "Document Signed",
    description:
      "Notify client that a legal document has been successfully processed.",
    category: "Legal Services",
    formData: {
      account: "",
      name: "Doc Signed",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, your settlement document has been signed and processed successfully.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "View Document" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "appointment-confirm",
    title: "Appointment Fixed",
    description: "Confirm salon or spa appointments automatically.",
    category: "Beauty & Wellness",
    formData: {
      account: "",
      name: "Appointment Fixed",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, your spa appointment is confirmed for Friday at 4 PM. We look forward to relaxing you.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Manage Booking" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "promo-wellness",
    title: "Wellness Promo",
    description: "Announce special wellness packages to loyal customers.",
    category: "Beauty & Wellness",
    formData: {
      account: "",
      name: "Wellness Promo",
      category: "MARKETING",
      language: "en_US",
      message:
        "Hi {{First Name}}, treat yourself! Get 20% off all massage packages this weekend only.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Book Now" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "service-due",
    title: "Service Due Reminder",
    description: "Remind car owners when their vehicle service is due.",
    category: "Automative Services",
    formData: {
      account: "",
      name: "Service Due",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, your vehicle is due for its scheduled maintenance. Book a slot soon.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Book Service" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "vehicle-ready",
    title: "Vehicle Ready",
    description: "Let customers know their car is ready for pickup.",
    category: "Automative Services",
    formData: {
      account: "",
      name: "Vehicle Ready",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, good news! Your car service is complete and it's ready for pickup.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "On my way" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "ticket-received",
    title: "Ticket Received",
    description: "Acknowledge receipt of a support ticket immediately.",
    category: "Tech Support / Saas",
    formData: {
      account: "",
      name: "Ticket Received",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, we received your support request. Our team is looking into it now.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "View Ticket" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "subscription-expiry",
    title: "Subscription Expiry",
    description:
      "Alert users when their subscription is about to renew or expire.",
    category: "Tech Support / Saas",
    formData: {
      account: "",
      name: "Sub Expiry",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, your subscription is expiring in 3 days. Renew now to avoid interruption.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Renew Now" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "maintenance-update",
    title: "Maintenance Update",
    description: "Update tenants on scheduled building maintenance.",
    category: "Property Management",
    formData: {
      account: "",
      name: "Maintenance Update",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, maintenance work is scheduled for the lobby tomorrow from 9 AM to 12 PM.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Okay" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
  {
    id: "rent-reminder",
    title: "Rent Reminder",
    description: "Friendly automated reminder for monthly rent payment.",
    category: "Property Management",
    formData: {
      account: "",
      name: "Rent Reminder",
      category: "UTILITY",
      language: "en_US",
      message:
        "Hi {{First Name}}, this is a reminder that rent for this month is due on the 1st.",
      hasHeader: false,
      headerType: "attachment",
      hasFooter: false,
      hasButton: true,
      buttons: [{ type: "Quick reply", text: "Pay Rent" }],
      hasAttachment: false,
      attachmentType: "image",
      headline: "",
      footerText: "",
      folder: "",
    } as TemplateFormData,
  },
];
